question_data = [
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Spitfire originated from a racing plane.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "There are 86400 seconds in a day.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "An eggplant is a vegetable.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Xenomorph from the science fiction film &quot;Alien&quot; has acidic blood.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Salt is 100% composed of Sodium.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "An atom contains a nucleus.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Comics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Deadpool&#039;s identity is Slade Wilson.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "hard",
        "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "hard",
        "question": "In Scandinavian languages, the letter &Aring; means river.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Roger Federer is a famous soccer player.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Time on Computers is measured via the EPOX System.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "medium",
        "question": "E = MC3",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Pistons were added to Minecraft in Beta 1.5.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "George Lucas directed the entire original Star Wars trilogy.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Celebrities",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Marilyn Monroe was born on July 1, 1926.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Zero factorial is equal to zero. ",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Klingons express emotion in art through opera and poetry.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Tokyo is the capital of Japan.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Android versions are named in alphabetical order.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Killer Whale is considered a type of dolphin.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In &quot;Star Trek&quot;, Klaang is a typical Klingon male.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "hard",
        "question": "During the Winter War, the amount of Soviet Union soliders that died or went missing was five times more than Finland&#039;s.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The scientific name for the Southern Lights is Aurora Australis?",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Cartoon & Animations",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A plant that has a life cycle for more than a year is known as an annual.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Jeb Bush was elected as Governor of Florida in 2002, starting his political career.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "hard",
        "question": "The man that shot Alexander Hamilton was named Aaron Burr.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Doki Doki Literature Club was developed in Japan.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "hard",
        "question": "Only one country in the world starts with the letter Q.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "hard",
        "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Ping-Pong originated in England",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
